/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExpenseId = IDL.Nat;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const LoginResult = IDL.Variant({
  'ok' : UserProfile,
  'errorMessage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExpense' : IDL.Func([Expense], [], []),
  'createExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAsOwner' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'loginAsSalesman' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'syncExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExpenseId = IDL.Nat;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const LoginResult = IDL.Variant({
    'ok' : UserProfile,
    'errorMessage' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExpense' : IDL.Func([Expense], [], []),
    'createExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAsOwner' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'loginAsSalesman' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'syncExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };