/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillId = IDL.Nat;
export const CustomerId = IDL.Nat;
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
  'availableInventory' : IDL.Nat,
  'piecesPerCase' : IDL.Nat,
});
export const Bill = IDL.Record({
  'id' : BillId,
  'gstApplied' : IDL.Bool,
  'creditAmount' : IDL.Nat,
  'gstAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'discount' : IDL.Nat,
  'customerId' : CustomerId,
  'gstRate' : IDL.Nat,
  'products' : IDL.Vec(Product),
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ExpenseId = IDL.Nat;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBill' : IDL.Func([Bill], [], []),
  'createCustomer' : IDL.Func([Customer], [], []),
  'createExpense' : IDL.Func([Expense], [], []),
  'createExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteBill' : IDL.Func([BillId], [], []),
  'deleteCustomer' : IDL.Func([CustomerId], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBill' : IDL.Func([BillId], [Bill], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'syncExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
  'updateCustomer' : IDL.Func([Customer], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillId = IDL.Nat;
  const CustomerId = IDL.Nat;
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
    'availableInventory' : IDL.Nat,
    'piecesPerCase' : IDL.Nat,
  });
  const Bill = IDL.Record({
    'id' : BillId,
    'gstApplied' : IDL.Bool,
    'creditAmount' : IDL.Nat,
    'gstAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'discount' : IDL.Nat,
    'customerId' : CustomerId,
    'gstRate' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ExpenseId = IDL.Nat;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBill' : IDL.Func([Bill], [], []),
    'createCustomer' : IDL.Func([Customer], [], []),
    'createExpense' : IDL.Func([Expense], [], []),
    'createExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteBill' : IDL.Func([BillId], [], []),
    'deleteCustomer' : IDL.Func([CustomerId], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBill' : IDL.Func([BillId], [Bill], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'syncExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
    'updateCustomer' : IDL.Func([Customer], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };