#!/bin/bash

# Publish Release APK Script for Frontline Distributors
# This script publishes the built APK from its versioned folder and generates a new unique download link

set -e  # Exit on error

echo "📤 Publishing Frontline Distributors APK..."
echo ""

# Check if we're in the right directory
if [ ! -f "build.gradle" ]; then
    echo "❌ Error: Must run this script from the frontend/android directory"
    echo "   cd frontend/android && ./scripts/publish-release-apk.sh"
    exit 1
fi

# Extract version info
VERSION_NAME=$(grep "versionName" app/build.gradle | sed 's/.*"\(.*\)".*/\1/')
VERSION_CODE=$(grep "versionCode" app/build.gradle | sed 's/[^0-9]*//g' | head -n 1)
EXPECTED_FILENAME="frontline-distributors-v${VERSION_NAME}-${VERSION_CODE}.apk"

echo "📦 Publishing version: v${VERSION_NAME} (code: ${VERSION_CODE})"
echo ""

# Find the most recent release folder for this version
LATEST_RELEASE_FOLDER=$(find dist/releases -type d -name "v${VERSION_NAME}-${VERSION_CODE}-*" 2>/dev/null | sort -r | head -n 1)

if [ -z "$LATEST_RELEASE_FOLDER" ]; then
    echo "⚠️  No versioned release folder found, checking dist/ root..."
    DIST_APK_PATH="dist/$EXPECTED_FILENAME"
    
    if [ ! -f "$DIST_APK_PATH" ]; then
        echo "❌ Error: APK not found in dist folder or versioned releases"
        echo "   Expected: $DIST_APK_PATH"
        echo ""
        echo "   Please build the APK first:"
        echo "   ./scripts/build-release-apk.sh"
        exit 1
    fi
    
    PUBLISH_SOURCE="$DIST_APK_PATH"
    echo "✓ Found APK in dist root: $PUBLISH_SOURCE"
else
    PUBLISH_SOURCE="$LATEST_RELEASE_FOLDER/$EXPECTED_FILENAME"
    
    if [ ! -f "$PUBLISH_SOURCE" ]; then
        echo "❌ Error: APK not found in release folder"
        echo "   Expected: $PUBLISH_SOURCE"
        exit 1
    fi
    
    echo "✓ Found APK in versioned release: $LATEST_RELEASE_FOLDER"
    echo "✓ APK path: $PUBLISH_SOURCE"
fi

# Get file size
if command -v du &> /dev/null; then
    SIZE=$(du -h "$PUBLISH_SOURCE" | cut -f1)
    echo "✓ Size: $SIZE"
fi

# Calculate checksum
if command -v shasum &> /dev/null; then
    CHECKSUM=$(shasum -a 256 "$PUBLISH_SOURCE" | cut -d' ' -f1)
    echo "✓ SHA256: $CHECKSUM"
elif command -v sha256sum &> /dev/null; then
    CHECKSUM=$(sha256sum "$PUBLISH_SOURCE" | cut -d' ' -f1)
    echo "✓ SHA256: $CHECKSUM"
fi

# Generate unique publish identifier with timestamp
PUBLISH_TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
PUBLISH_ID="v${VERSION_NAME}-${VERSION_CODE}-${PUBLISH_TIMESTAMP}"

# Write publish metadata
if [ -n "$LATEST_RELEASE_FOLDER" ]; then
    PUBLISH_METADATA_PATH="$LATEST_RELEASE_FOLDER/publish-metadata.json"
else
    PUBLISH_METADATA_PATH="dist/publish-metadata.json"
fi

cat > "$PUBLISH_METADATA_PATH" <<EOF
{
  "publishId": "${PUBLISH_ID}",
  "versionName": "${VERSION_NAME}",
  "versionCode": ${VERSION_CODE},
  "filename": "${EXPECTED_FILENAME}",
  "publishTimestamp": "${PUBLISH_TIMESTAMP}",
  "sha256": "${CHECKSUM:-unknown}",
  "sourcePath": "${PUBLISH_SOURCE}",
  "uniqueDownloadUrl": "Will be generated by Caffeine platform"
}
EOF

echo "✓ Publish metadata: $PUBLISH_METADATA_PATH"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📤 PUBLISHING APK WITH UNIQUE DOWNLOAD URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This APK will be published through the Caffeine platform with a"
echo "brand-new, unique download URL for this specific build."
echo ""
echo "The Caffeine build system will automatically:"
echo "  1. Upload this APK from the versioned release folder"
echo "  2. Generate a NEW unique download URL (not /latest)"
echo "  3. Make it publicly accessible for distribution"
echo ""
echo "🔗 NEW UNIQUE DOWNLOAD LINK WILL BE GENERATED"
echo ""
echo "   Publish ID: $PUBLISH_ID"
echo "   Source: $PUBLISH_SOURCE"
echo ""
echo "   ✅ This ensures a fresh, publicly reachable download URL"
echo "   ✅ Each build gets its own unique versioned URL"
echo "   ⚠️  Do NOT reuse previous /latest links!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Build Details:"
echo "   File: $EXPECTED_FILENAME"
echo "   Version: v${VERSION_NAME} (code ${VERSION_CODE})"
echo "   Source: $PUBLISH_SOURCE"
echo "   Publish ID: $PUBLISH_ID"
if [ -n "$CHECKSUM" ]; then
    echo "   SHA256: $CHECKSUM"
fi
echo ""
echo "✅ APK is ready for Caffeine platform publishing"
echo ""
echo "🌐 A NEW publicly reachable download link will be provided"
echo "   by the Caffeine build system after publishing completes."
echo ""
echo "   The link will be in the format:"
echo "   https://api.caffeine.build/download/apk/frontline-distributors/${PUBLISH_ID}"
echo "   (or similar unique URL pattern)"
echo ""
